DROP TABLE IF EXISTS numbers;

CREATE TABLE numbers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  person_id INTEGER NOT NULL,
  location TEXT NOT NULL,
  FOREIGN KEY (person_id) REFERENCES person(id)
);

CREATE TABLE person (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  number INTEGER NOT NULL
)
